- hosts: all
  tasks:
   - name: Install python pip
     apt:
      name: python3-pip
      state: present
   - name: Install docker-py
     apt:
      name: python3-docker
      state: present
   - name: Removendo container "{{MODULO}}_homologacao2"
     docker_container:
        name: "{{MODULO}}_homologacao2"
        state: absent

   - name: Start the container "{{MODULO}}_homologacao"
     docker_container:
        name: "{{MODULO}}_homologacao"
        image: "192.168.70.24:5000/{{MODULO}}:{{DOCKER_TAG}}"
        state: started
        pull: true
        recreate: yes
        ports:
           - 0.0.0.0:8082:8080
